theme = "casper"
BaseUrl= ""
LanguageCode= "en-us"
Title= "Just Random Thoughtsssss"
paginate = 5
DisqusShortname = "YOUR_SHORT_NAME_HERE"
#Copyright = "MIT lisence"
canonifyurls = false


[params]
  description = "about anything techie"
  cover = "images/cover.jpg"
  author = "Filippos Vasilakis"
  authorlocation = "Stockholm, Sweden & Athens, Greece"
  authorwebsite = "http://fil.vasilak.is"
  bio = "Web Engineer"
  logo = "images/logo.jpg"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "vasilakisfil"
  twitterName = "vasilakisfil"
  # facebookName = false
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "vasilakisfil"

[[menu.main]]
  name = "Home"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
